services:
    symfony:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "80:80"
            - "22:22"
        volumes:
            - ".:/var/www/html"
            - "./default.conf:/etc/apache2/sites-available/000-default.conf"
            - symfony_var:/var/www/html/var
            - composer_vendor:/var/www/html/vendor
            - composer_cache:/root/.composer/cache
            - symfony_migrations:/var/www/html/migrations
            - "./lib:/var/www/lib"
        environment:
            - XDEBUG_ENABLED=0
            - PHP_VERSION=8.2
        networks:
            - web
    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - "db_volume:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "database"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "root"
        networks:
            - web
volumes:
    symfony_var:
    symfony_migrations:
    composer_vendor:
    composer_cache:
    db_volume:
        driver: local
networks:
    web:
        name: web
        driver: bridge
